### ISSUE TITLE
Blazor WASM debugging and hot reload doesn't work

### ISSUE THREAD

**Issue by dotnetian** [JetBrains/aspire-plugin#129]
I have an Aspire project, including a new Blazor app using client and server rendering. But when I run the Aspire Apphost and place breakpoints on the code or try doing a hot reload, it doesn't work.

**Comment by dotnetian** [comment]
Any updates??

**Comment by rafaelldi** [comment]
@jamsoft Sorry to hear that. 

> It's completely broken as far as I can tell.

To be honest, it's not true. Most .NET project types work without problems, and almost only Blazor Wasm projects have some specifics, so they are not supported yet. We are discussing how to properly implement the support for such projects.
