### ISSUE TITLE
Support Test Debugging?

### ISSUE THREAD

**Issue by jhancock-taxa** [JetBrains/aspire-plugin#185]
Right now if you choose to debug unit tests that use the Aspire host, you can step through the code for the test itself, but any of the code that is executed in the projects in the aspire host, can't have breakpoints set and thus you can't debug what's happening in your projects that the test is calling.

Is it possible to enable this so that you get full debugging of any projects that are spun up during the test phase using the standard Aspire tooling for Tests?

**Comment by rafaelldi** [comment]
Unfortunately, right now it's not supported in the plugin

**Comment by jhancock-taxa** [comment]
It would be awesome if the plugin could support it. Vs.net does, VS Code doesn't so Mac Users can't properly debug integration tests right now.
