### ISSUE TITLE
Support for automatic reload

### ISSUE THREAD

**Issue by Kralizek** [JetBrains/aspire-plugin#200]
Nowadays when I work in Rider on a Aspire-enabled solution I have to choose between the comfort offered by this plugin (database attachment is a crown pearl) and the comfort offered by `dotnet watch run` the AppHost project.

Ideally, I'd love to be able to use the plugin while retaining the automatic restart of services based on file system modifications.

It would be extra luxury if a service being restarted during a debugging session is automatically attached again.

**Comment by rafaelldi** [comment]
Hi! `dotnet watch` uses hot reload as far as I understand. The plugin supports hot reload too. Once you make the changes, you will see such a notification and can apply the changes.

![image](https://github.com/rafaelldi/aspire-plugin/assets/16965141/4d352141-83b7-4d82-a10e-f4790810928d)

**Comment by Kralizek** [comment]
Is there a way to apply those changes automatically?

**Comment by rafaelldi** [comment]
It's a feature of the Rider itself, so you can check it here https://www.jetbrains.com/help/rider/Hot_Reload.html

**Comment by rafaelldi** [comment]
Also you can vote for this feature https://youtrack.jetbrains.com/issue/RIDER-68499/Apply-Hot-Reload-changes-on-file-save
