### ISSUE TITLE
Feature Request: Shortcuts for restarting Projects

### ISSUE THREAD

**Issue by g-martin772** [JetBrains/aspire-plugin#209]
A keyboard shortcut to restart/reboot+debug the selected/recognised current project would be very nice. Unfortunately I am not familiar with Jetbrain's IDE plugin development, but I hope this is doable.

**Comment by rafaelldi** [comment]
You can create a shortcut for yourself. Just search for `aspire` in the keymap settings and you will see all the actions

![image](https://github.com/user-attachments/assets/f778c826-b184-4fc3-b847-7b48144adb4e)

**Comment by g-martin772** [comment]
Yes, but that is only useful to some extent because you still have to click the resource every time you want to restart it. Once it loses focus or you navigate to another tool window or editor it wont work. I imagined something more like the "Build current project" action, that detects what you are currently editing and then select the project accordingly. Not sure if something like that is planned. It was just an idea.

**Comment by rafaelldi** [comment]
I won't add keyboard shortcuts, because it's hard to choose ones that are convenient for all keyboard layouts. But I made a fix to get a focused project from context. That way you can add a shortcut yourself, Rider will try to detect the project and restart/stop the corresponding resource.

**Comment by g-martin772** [comment]
Sounds great, thanks!
