### ISSUE TITLE
Cannot restart .NET project services

### ISSUE THREAD

**Issue by jack775544** [JetBrains/aspire-plugin#226]
Rider Version: 2024.1.4
Plugin Version: 1.2.0
Aspire Version: 8.1.0

I have noticed that recently I can no longer restart project resources from the services window. The buttons are there but greyed out. I believe this may have coincided with the release of Aspire 8.1.0 however I am not certain of this.

![image](https://github.com/user-attachments/assets/0d8b4b2d-5455-4032-8093-f3bce62cb028)

I have tried a few things, none which have made the feature work again.

* Downgrading Aspire version in project to 8.0.2.
* Using latest Rider RC release (2024.2 RC1, plugin version 1.3.0).
* Creating a new Aspire project `dotnet new aspire-starter`.

None of these things have enabled the restart buttons. The only thing I have not tried is downgrading the Aspire workload, since that is a bit tricker to do.

**Comment by rafaelldi** [comment]
Thanks! Yes, they changed some of the environment variables that I used for this feature

**Comment by LManBen** [comment]
Look like this issues is back again with the 8.2.0 version ...

**Comment by rafaelldi** [comment]
@LManBen what version of the plugin do you have?

**Comment by LManBen** [comment]
@rafaelldi  I have the bundled 1.3.0
