### ISSUE TITLE
Resource Options aren't available on macOS

### ISSUE THREAD

**Issue by dotnetian** [JetBrains/aspire-plugin#236]
![image](https://github.com/user-attachments/assets/d6112b24-2684-49a5-a05c-2f6f37d26825)

The Aspire app is running and everything works well. But in macOS, the buttons to Restart Resource and other ones are always disabled.

I tested this on Windows and it was working fine.

**Comment by rafaelldi** [comment]
Hello. What version of the plugin do you use? And what version of the Aspire workload?

**Comment by dotnetian** [comment]
Plugin is the latest version (1.2.0)

And these are my .NET Workloads:

Installed Workload Id      Manifest Version      Installation Source
--------------------------------------------------------------------
aspire                     8.1.0/8.0.100         SDK 8.0.300

**Comment by rafaelldi** [comment]
Thanks. The latest version is 1.4.1 (available for Rider 2024.2). Probably, this issue is already fixed here #226. I'm going to close this issue for now, feel free to reopen it if it still doesn't work for you in version 1.4.1.
