### ISSUE TITLE
Dáhboard can not start in MacOS(M3) but start OK in windows

### ISSUE THREAD

**Issue by Mike6x** [JetBrains/aspire-plugin#238]
When I create a test project and run with Rider /windows => everything is OK. But when I dun it in MACOS(M3) then I have problems:

<img width="1523" alt="image" src="https://github.com/user-attachments/assets/02be99ef-8da2-4eed-bd7a-8d6f1c844878">

`info: Aspire.Hosting.DistributedApplication[0]
      Now listening on: https://localhost:17299
info: Aspire.Hosting.DistributedApplication[0]
      Login to the dashboard at https://localhost:17299/login?t=6c32b67f-8d36-44a1-a04d-9fbf53c69baa
info: Aspire.Hosting.DistributedApplication[0]
      Distributed application started. Press Ctrl+C to shut down.
fail: Aspire.Hosting.Dcp.dcpctrl.ExecutableReconciler[0]
      failed to start a process {"Executable": {"name":"aspire-dashboard-mjwqvcpq"}, "Reconciliation": 5, "error": "exec: \"dotnet\": executable file not found in $PATH"}
fail: Aspire.Hosting.Dcp.dcpctrl.ExecutableReconciler[0]
      failed to start Executable        {"Executable": {"name":"aspire-dashboard-mjwqvcpq"}, "Reconciliation": 5, "error": "exec: \"dotnet\": executable file not found in $PATH"}
`

My ent:
`
@MIKEs-MacBook-Pro MyUnicorn % dotnet workload list

Installed Workload Id      Manifest Version      Installation Source
--------------------------------------------------------------------
aspire                     8.1.0/8.0.100         SDK 8.0.300        

Use `dotnet workload search` to find additional workloads to install.

MIKs-MacBook-Pro MyUnicorn % 

`

`MacBook-Pro MyUnicorn % dotnet --info
.NET SDK:
 Version:           8.0.303
 Commit:            29ab8e3268
 Workload version:  8.0.300-manifests.56cd0383
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.5
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /Users/tuanpa/.dotnet/sdk/8.0.303/

.NET workloads installed:
 [aspire]
   Installation Source: SDK 8.0.300
   Manifest Version:    8.1.0/8.0.100
   Manifest Path:       /Users/tuanpa/.dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.aspire/8.1.0/WorkloadManifest.json
   Install Type:        FileBased

Host:
  Version:      8.0.7
  Architecture: arm64
  Commit:       2aade6beb0

.NET SDKs installed:
  8.0.303 [/Users/tuanpa/.dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.7 [/Users/tuanpa/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.7 [/Users/tuanpa/.dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

MacBook-Pro MyUnicorn % dotnet --list-sdks
8.0.303 [/Users/tuanpa/.dotnet/sdk]

-MacBook-Pro MyUnicorn % dotnet --list-runtimes
Microsoft.AspNetCore.App 8.0.7 [/Users/tuanpa/.dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 8.0.7 [/Users/tuanpa/.dotnet/shared/Microsoft.NETCore.App]
`

**Comment by rafaelldi** [comment]
It says it can't find the `dotnet` executable in the `PATH` environment variable.

> \"dotnet\": executable file not found in $PATH"

Do you have one? Have you tried starting with `dotnet run` instead of Rider? I suppose it might be a problem in Aspire and not in the plugin.
