### ISSUE TITLE
Only one database gets added to database panel if multiple databases are present

### ISSUE THREAD

**Issue by Kralizek** [JetBrains/aspire-plugin#243]
**Describe the bug**
My AppHost project contains more than database on the same PostgreSQL container. Only the first one is accessible from the Database panel.

**To Reproduce**
```
var password = builder.AddParameter("DatabasePassword").ExcludeFromManifest();

var database = builder.AddPostgres("postgres", password: password)
    .WithDataVolume("npgsql-experiment");

var dbOne = database.AddDatabase("db1");
var dbTwo = database.AddDatabase("db2");
var dbThree = database.AddDatabase("db3");
```

**Expected behavior**
All database should be added to the panel when the application is started.

**System information:**
 - OS: Windows
 - .NET version: 8.0
 - JetBrains Rider version: 2024.2.3
 - Aspire plugin version: 1.3.0
 - Aspire workload version: 8.2.0

**Comment by Kralizek** [comment]
@rafaelldi were you able to reproduce this issue?

**Comment by Kralizek** [comment]
Here is a simple repro that already shows the behavior, but I'm not sure if this is because the databases are not created yet. If that's the case, I can fix that.

https://github.com/Kralizek/RiderAspireMultipleDatabases

**Comment by rafaelldi** [comment]
I have three of them:

![image](https://github.com/user-attachments/assets/6174cfb9-3a2b-420b-bafe-800bd718bd06)

**Comment by Kralizek** [comment]
Having three of them happens 5% of the times (guesstimate)

**Comment by rafaelldi** [comment]
Thank you for your help! It should be fixed in the next release #283

**Comment by Kralizek** [comment]
I gave a quick look at the PR for curiosity. Now, my Kotlin knowledge amounts to the time I've been looking at your PR, but it feels weird it even showed more than one database at all.

Or am I blind to something in the previous code?

**Comment by rafaelldi** [comment]
There was a race. It depended on the order in which resources and connection strings came to us. Even if three connection strings had already arrived, we always chose one. But if they came one by one, everything was fine.
