### ISSUE TITLE
Unable to debug AppHost

### ISSUE THREAD

**Issue by cecilphillip** [JetBrains/aspire-plugin#247]
**Describe the bug**
I am able to debug other projects in the solution but breakpoints don't get trigger in the AppHost.
This happens when using the AppHost configuration, but breakpoints get trigger when I use the ".NET Launch settings profile" instead

**To Reproduce**
- Create a new Aspire starter application
- Set a breakpoint in the appHost Program.cs

**Expected behavior**

**Screenshots**

**Reproducing sample**
Link to a test project to reproduce the bug.

**System information:**
 - OS: MacOS
 - .NET version: 8
 - JetBrains Rider version: 2024.2.3
 - Aspire plugin version: 1.3.0
 - Aspire workload version: 8.2.0

**Comment by rafaelldi** [comment]
@cecilphillip Thank you for the feedback. Actually, "it's not a bug, it's a feature". I intentionally run the Host project without a debugger attached to simplify the user experience. From what I understand, Host project is more like `docker-compose.yml` with the dependencies described, and you probably don't need to debug it. What are your thoughts on this? Do you have scenarios where the debugger is necessary?

**Comment by rafaelldi** [comment]
Thank you! I'll consider to support debugging

**Comment by ForNeVeR** [comment]
In other Rider configurations (without Aspire), Multilaunch configs allow the user to choose what they want and what they don't want to debug.

Perhaps we can add a checkbox to the Aspire configuration (unchecked by default if we consider it a better choice), to create a separate debug session for the Host projects?

**Comment by rafaelldi** [comment]
Nice idea!

**Comment by rafaelldi** [comment]
I decided to keep it simple. Just enable host debugging if it's a debugging session. I think this is the clearest option.
