### ISSUE TITLE
Windows cannot find 'https://localhost:xxxx' when starting Aspire project

### ISSUE THREAD

**Issue by thomasvdb** [JetBrains/aspire-plugin#263]
**Describe the bug**
Since the upgrade to version 1.5.0, I get an error pop-up for each project starting up (about 14 times) stating the following error message:
"Windows cannot find 'http://localhost:50622;http://localhost:50632'. Make sure you typed the name correctly, and then try again"

Everything starts up correctly however so I can still work but it's a bit annoying of course.

**To Reproduce**
1. Start the Aspire apphost project

**Expected behavior**
No error popups.

**Screenshots**
![Schermafbeelding 2024-10-11 101222](https://github.com/user-attachments/assets/397f5116-47fa-45e1-bdc1-0f610438249b)

**System information:**
 - OS: Windows
 - .NET version: 8
 - JetBrains Rider version: JetBrains Rider 2024.2.6
 - Aspire plugin version: 1.5.0
 - Aspire workload version: 8.1.0

**Comment by rafaelldi** [comment]
@thomasvdb Thank you for the report! It should be fixed in the next release

**Comment by rafaelldi** [comment]
It wasn't implemented properly before. Now I decided to align it with the behavior of `launchSettings.json`. You can disable the browser launching with this `launchBrowser` setting.

<img width="437" alt="image" src="https://github.com/user-attachments/assets/cb9e2891-0823-4a20-af5e-496a34d7a9a9">

**Comment by thomasvdb** [comment]
To be honest, I liked the previous behavior (and it's also the default behavior in Visual Studio).
If I need the complete Aspire setup, I'll start the Aspire project and only the dashboard is launched. I can then decide myself via the dashboard which URLs I want to open.

If I only need to run a certain project (for development or debugging purposes), I'll start that specific project but then the project should launch automatically.

Now I have to change the launchSettings.json file between each scenario.

**Comment by rafaelldi** [comment]
Unfortunately, the current design of Aspire's integration with the IDE relies on `launchSettings.json`.
I can add a separate setting for you to disable browser launch for child projects.

**Comment by rafaelldi** [comment]
@thomasvdb Here is the new setting

<img width="738" alt="image" src="https://github.com/user-attachments/assets/1c62be52-385a-4055-90bf-86d1bef668a5">

**Comment by thomasvdb** [comment]
That's awesome, thanks a lot!
