### ISSUE TITLE
Hot Reload "Apply Changes" doesn't toggle a browser update when using Blazor

### ISSUE THREAD

**Issue by TheRubble** [JetBrains/aspire-plugin#273]
**Describe the bug**
Hot Reload "Apply Changes" doesn't toggle a browser update when using Blazor. This works fine in the VS2022 Preview (17.12.0 Preview 4.0)

**To Reproduce**
Steps to reproduce the behaviour:
1. Create an aspire starter application.
2. Run the application.
3. Change the Home component in the Blazor application to have a different hello world message and apply changes.

**Expected behaviour**
1. Browser should reflect the change.
2. 
**System information:**
 - OS: Windows 11 
 - .NET version: 8
 - JetBrains Rider version: 2024.2.6
 - Aspire plugin version:  1.4.1
 - Aspire workload version: 9.0.0-rc.1.24511.1

**Comment by rafaelldi** [comment]
Hello!

> Aspire plugin version: 1.4.1

The Blazor hot reload was added in the `v1.5.0` version of the plugin. Please, check it in the latest version.

**Comment by TheRubble** [comment]
![image](https://github.com/user-attachments/assets/4188d762-9adc-4474-b05d-e5e2235527b0)

Updated to this version of the plugin and sadly it's still not working.

**Comment by rafaelldi** [comment]
Thanks. Can you run the same project not through Aspire, but using the `launchSettings` run configuration? Does the hot reload work in this case? The problem may be in Rider itself

**Comment by TheRubble** [comment]
Ok so that's not working either.... I never have much luck with Rider and hot reload. Dotnet Watch works fine.

**Comment by TheRubble** [comment]
So I've changed the setup to this:
![image](https://github.com/user-attachments/assets/86e8e0e5-a12c-449f-9234-3951d3ed70b1)
That works fine in Rider when using the "Watch" profile but not when using Aspire. I've also changed Aspire to use the profile.
![image](https://github.com/user-attachments/assets/9dc5496d-f3f8-4ac4-8f5f-131e0dddf15f)

**Comment by rafaelldi** [comment]
> Ok so that's not working either

I've found this ticket https://youtrack.jetbrains.com/issue/RIDER-118344/Hot-reload-doesnt-work-for-Blazor-WASM, you can follow it. This should be fixed in Rider itself, because in the plugin we use the Rider mechanism and can't do anything on our side.

>  I never have much luck with Rider and hot reload.

I've just tested it, and for dotnet 8 it works fine. Anyway, if you have any hot reload issues, you can open a ticket in our YouTrack and they will be addressed by my colleagues.

> That works fine in Rider when using the "Watch" profile but not when using Aspire

Yes, unfortunately for Aspire it doesn't work. It should be `“commandName”: “Project”`.
