### ISSUE TITLE
 .net 9 aspire "error": "no runner found for execution type 'IDE'"

### ISSUE THREAD

**Issue by huberttrueselftrueme** [JetBrains/aspire-plugin#292]
**Describe the bug**
After upgrade form .net 8 to .net 9 Aspire project stop working. It seams that project resources can't run. 
The same code work when run manually  dotnet run form terminal or VS Core. 
I tested, and reproduce this behaviour with existing projects,  new project to existing solution, new solution  form .net aspire template .net 9. 

**To Reproduce**
1. Install .NET 9
2. Create solution form .net aspire starter tempalte
3. debug / run

**Screenshots**
![image](https://github.com/user-attachments/assets/4ad16453-96dd-4e36-baa2-19e33ec20199)

**Logs**
      Updating application model resource mongodb with Container resource mongodb-zrsgyxbk
info: Aspire.Hosting.Dcp.dcpctrl.ServiceReconciler[0]
      service /mongodb-mongoexpress is now in state Ready       {"ServiceName": {"name":"mongodb-mongoexpress"}, "Reconciliation": 13}
trce: Aspire.Hosting.Dcp.ApplicationExecutor[0]
      Updating application model resource mongodb-mongoexpress with Container resource mongodb-mongoexpress-kucnkfcx
info: Aspire.Hosting.Dcp.dcpctrl.ServiceReconciler[0]
      service /mongodb is now in state Ready    {"ServiceName": {"name":"mongodb"}, "Reconciliation": 15}
trce: Aspire.Hosting.Dcp.ApplicationExecutor[0]
      Updating application model resource mongodb with Container resource mongodb-zrsgyxbk
trce: Aspire.Hosting.Dcp.ApplicationExecutor[0]
      Updating application model resource admin with Executable resource admin-qynsqkjp
fail: Aspire.Hosting.Dcp.dcpctrl.ExecutableReconciler[0]
      the Executable cannot be run and will be marked as failed to start        {"Executable": {"name":"admin-qynsqkjp"}, "Reconciliation": 7, "error": "no runner found for execution type 'IDE'"}
fail: Aspire.Hosting.Dcp.dcpctrl.ExecutableReconciler[0]
      the Executable cannot be run and will be marked as failed to start        {"Executable": {"name":"api-zxnhmxrq"}, "Reconciliation": 8, "error": "no runner found for execution type 'IDE'"}
trce: Aspire.Hosting.Dcp.ApplicationExecutor[0]
      Updating application model resource api with Executable resource api-zxnhmxrq
trce: Aspire.Hosting.Dcp.ApplicationExecutor[0]
      Updating application model resource admin with Executable resource admin-qynsqkjp
trce: Aspire.Hosting.Dcp.ApplicationExecutor[0]

**System information:**
.NET SDK:
 Version:           9.0.100
 Commit:            59db016f11
 Workload version:  9.0.100-manifests.c6f19616
 MSBuild version:   17.12.7+5b8665660

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  15.1
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/9.0.100/
.NET workloads installed:
 [maui]
   Installation Source: SDK 9.0.100
   Manifest Version:    9.0.0/9.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/9.0.100/microsoft.net.sdk.maui/9.0.0/WorkloadManifest.json
   Install Type:        FileBased
Configured to use loose manifests when installing new manifests.
Host:
  Version:      9.0.0
  Architecture: arm64
  Commit:       9d5a6a9aa4
.NET SDKs installed:
  9.0.100 [/usr/local/share/dotnet/sdk]
.NET runtimes installed:
  Microsoft.AspNetCore.App 9.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 9.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Other architectures found:
  None
Environment variables:
  Not set
global.json file:
  Not found
**Additional context**

![image](https://github.com/user-attachments/assets/ad4529ab-c31f-4967-adf3-7aa2d49067ad)

**Comment by Kevdome3000** [comment]
experiencing same issue

**Comment by rafaelldi** [comment]
Thanks for the report, I'm checking it.

**Comment by rafaelldi** [comment]
Unfortunately, I can't reproduce this (I've tried macOS and Windows versions). Could you please share your template solution? And maybe you can collect logs (please enable Aspire trace scenarios via Help | Diagnostic Tools | Choose Trace Scenarios | Aspire, reproduce the problem and collect logs via Help | Collect Logs)?

**Comment by huberttrueselftrueme** [comment]
I created this repo. 
https://github.com/huberttrueselftrueme/rideraspireerror 
Also i included .run file form rider with run configuration. 

My thinking is maybe we are missing some permissions on macOS system to ran separate projects. ?? 

Last thing. Yesterday when I update rider to 2024.3 to newest Aspire.Plugin i saw form rider perspective was 1.6 version. 
After some digging I notice that on plugin repo page there is version 1.6.3 so i install it manually. I get the same error on both version of plugin.

**Comment by rafaelldi** [comment]
@huberttrueselftrueme Thanks! I've managed to reproduce it. Investigating.

**Comment by rafaelldi** [comment]
So, it should be fixed in the 1.6.4. release of the plugin.

**Comment by rafaelldi** [comment]
@Tielem Hi! No, the release has been available since 14 November; you can check here: https://plugins.jetbrains.com/plugin/23289--net-aspire/versions/stable/633994.

The pipeline you mentioned is not related to the release one, it is just about updating the changelog file.

**Comment by jkappers** [comment]
@rafaelldi FWIW, I had to use the marketplace and install from disk to get this update. Installing it from the IDE gave 1.6.0

**Comment by matt-goldman** [comment]
Same for me:
![image](https://github.com/user-attachments/assets/302c092b-8460-4305-a00d-04c44e01820b)

After downloading and installing the zip, I now have an update to 1.6.6 available:
![image](https://github.com/user-attachments/assets/9c562b6c-9a4a-4949-8746-f19aecc706bd)

But the good news is it's resolved the issue, so I'm happy 😊

**Comment by rafaelldi** [comment]
Unfortunately, this is a known issue. I hope it will be fixed soon.

**Comment by lprichar** [comment]
I got this error in Visual Studio 17.11.6; Aspire @ 9.0.0; .NET @ 9.0.100.  It was working when I left for holiday and when I returned it started producing this error.  When I closed and reopened Visual Studio the error went away.

**Comment by omaristalis** [comment]
> Sorry not really relevant to this thread...

Same - restarting VS made the error go away for me too.

**Comment by garrettlondon1** [comment]
Now getting this error on Mac again on 9.0.100 VSCode dotnet run on the AppHost, worked previously

**Comment by LeszekKalibrate** [comment]
> > Sorry not really relevant to this thread...
> 
> Same - restarting VS made the error go away for me too.

Needed to restart Windows.
