### ISSUE TITLE
Restarting a service in the dashboard breaks the connection with the plugin

### ISSUE THREAD

**Issue by Kralizek** [JetBrains/aspire-plugin#295]
**Describe the bug**
In Aspire 9, when restarting a service from the dashboard breaks the connection with the plugin.

**To Reproduce**
- Create an application using Aspire 9
- Start it from Rider
- Restart a service
- Try to perform any operation on the same service from the plugin

**Expected behavior**
The plugin should somehow be able to refresh its state when a service is restarted in Aspire 9

**System information:**
 - OS: Windows 11
 - .NET version: 9.0.0
 - JetBrains Rider version: 2024.3
 - Aspire plugin version: 1.6.0
 - Aspire workload version: none.

**Comment by rafaelldi** [comment]
Hello! Have you tried the latest release version 1.6.4?

**Comment by Kralizek** [comment]
Uhm no, honestly I'm quite annoyed I am stuck with the shipped version of the plug-in

**Comment by rafaelldi** [comment]
@Juulsn Hi! This error comes from Aspire itself, not from the plugin. Do you see the same error when you restart the service from the Aspire dashboard? Anyway, it doesn't relate to the original issue because the mechanism for restarting services in v1.6.0 and 1.6.4 is completely different.

<img width="1895" alt="image" src="https://github.com/user-attachments/assets/d685b1dc-0c17-4d8c-8528-349bc483dc37">

**Comment by rafaelldi** [comment]
> Uhm no, honestly I'm quite annoyed I am stuck with the shipped version of the plug-in

Yeah, I can understand that. Unfortunately, there's nothing I can do about it. I hope that plugin will be properly bundled in the 2025.1 version. The version 1.6.4 should be shipped with one of the next Rider bugfixes.

**Comment by Juulsn** [comment]
Upload id: 2024_11_19_C5rjTuqeL3ozpyzkFkxwDv

**Comment by rafaelldi** [comment]
@Juulsn Thank you, but, to be honest, I don't know how to download with just upload id. If you want, you can create an issue in our YouTrack and attach it there https://youtrack.jetbrains.com/issues/RIDER
