### ISSUE TITLE
Prevent plugin from launching all child project swaggers

### ISSUE THREAD

**Issue by digifidevelopment** [JetBrains/aspire-plugin#297]
Describe the bug
All swaggers are launching in browser when starting AppHost project with Aspire.
This was not the case before upgrading to Rider to 2024.3.

To Reproduce
Create some applications and run AppHost project, all swaggers for each project will launch in browser.

System information:
OS: Windows 11
.NET version: 9.0.0
JetBrains Rider version: 2024.3
Aspire plugin version: 1.6.0

Are there any settings to avoid this?
Should not have to modify all launch settings in respective project.

**Comment by rafaelldi** [comment]
Hello! There is a special setting for that:

<img width="738" alt="image" src="https://github.com/user-attachments/assets/6e019c17-cca9-4ecc-bdda-c628c5d3374a">
