### ISSUE TITLE
Restarting project from services panel no longer works

### ISSUE THREAD

**Issue by jack775544** [JetBrains/aspire-plugin#298]
**Describe the bug**

I have updated Rider to 2024.3 and the plugin to 1.6.4 and I can no longer restart projects from the services panel. My current Aspire version is 8.2.1.

If I update the Aspire AppHost to 9.0.0, the restart button will now not be greyed out but clicking will only restart the project and not rebuild it like it did before, meaning that any changes to the source code will now no longer be reflected in the restarted project.

In addition, the restart with debug button that was previously on the services panel has now disappeared as well.

**To Reproduce**
1. Start apphost project
2. Restart button is greyed out

![image](https://github.com/user-attachments/assets/907f733c-1e42-4610-89ba-4ae96e2a12e0)

After updating to Aspire 9:

![image](https://github.com/user-attachments/assets/8a35ce99-66f6-41dd-afeb-5c8fd58fb429)

**Expected behavior**
* Restart button works on all Aspire version
* Restart with debug button appears again.

**System information:**
 - OS: Windows 11 (22631)
 - .NET version: 8.0.404
 - JetBrains Rider version: 2024.3
 - Aspire plugin version: 1.6.4
 - Aspire workload version: 8.2.1

**Comment by jack775544** [comment]
Downgrading to 1.6.0 of the plugin seems to restore functionality back to normal.

**Comment by rafaelldi** [comment]
Hello! This is not a bug, we've switched to the Aspire Dashboard API instead of our internal implementation. Unfortunately, it looks like it's only available starting with .NET Aspire 9.0, so it's not supported for previous versions. And the Dashboard API doesn't have a feature like restarting with a debugger, so it's not available anymore.

https://learn.microsoft.com/en-us/dotnet/aspire/whats-new/dotnet-aspire-9?tabs=windows#manage-resource-lifecycle

**Comment by rafaelldi** [comment]
> clicking will only restart the project and not rebuild it like it did before, meaning that any changes to the source code will now no longer be reflected in the restarted project

Sorry, I've missed that part. Yes, we should build the project before restarting it.

**Comment by jack775544** [comment]
Not being able to restart with a debugger is pretty annoying since that is the easiest way to debug startup code.

I know this would be for Visual Studio, but in that section it does mention

> For project resources, when the debugger is attached, it's reattached on restart.

Is it not be possible to store some internal state inside of the plugin that contains a list of projects that want to be debugged (and is added to by pressing the restart with debugger button). Then upon receiving a start/restart command from Aspire, automatically attach a debugger to the project and remove it from the list.


Or failing that, would it be possible to but a button on the services panel for the project to attach a debugger to a running process so I would not have to go hunting for it in the attach to process dialog.

**Comment by rafaelldi** [comment]
Thank you, I'll think about it.

**Comment by JohnGalt1717** [comment]
I know this is closed but Rider is blocking just selecting a project and restarting it, even though you can do this in vs.net and vs code. Can we get this functionality back? It's killer for the inner loop when fixing startup stuff.

**Comment by rafaelldi** [comment]
@JohnGalt1717 Hi! Do you mean restarting from the Service tool window? I've fixed this issue in the #336. The fix should be available in the next 1.7.2 release.

**Comment by JohnGalt1717** [comment]
From the debug window where it shows tabs for each of the running project, in the early days Rider would let you restart an individual item, but now the "rerun" button is disabled. It would be nice to, from that same window have the rerun button stop, rebuild and then start the project again.

**Comment by rafaelldi** [comment]
@JohnGalt1717 I checked, it seems to be a limitation of Aspire. If a particular service has been stopped, it cannot be restarted from outside Aspire. You can restart projects from Rider's Services tool window. There have been some issues with this, but they should be fixed in the latest version 1.7.3.

<img width="987" alt="Image" src="https://github.com/user-attachments/assets/01c6ede3-f0a3-41cf-b6de-d44834324d89" />

**Comment by jack775544** [comment]
Is there any chance of this services panel fix being made available on a non EAP version of rider?
