### ISSUE TITLE
Can run AppHost under .NET 9

### ISSUE THREAD

**Issue by cecilphillip** [JetBrains/aspire-plugin#306]
**Describe the bug**
Unable to change the target framework in Rider's Run/Debug configuration for the Aspire Apphost.

**To Reproduce**
1. Upgrade [existing project](https://github.com/cecilphillip/shadowshop) to [Aspire v9](https://learn.microsoft.com/en-us/dotnet/aspire/get-started/upgrade-to-aspire-9?pivots=dotnet-cli).
2. Open Debug configuration for AppHost
3. Try to change target framework from 8 to 9

**Expected behavior**
Run and debug AppHost using net9.0 TFM

**Screenshots**
<img width="960" alt="Screenshot 2024-11-22 at 9 57 17 PM" src="https://github.com/user-attachments/assets/aabcf01b-5ce5-423c-bb80-f04bb7195c35">

**Logs**
Archive with collected logs. [Here](https://www.jetbrains.com/help/rider/NET_Aspire_troubleshooting.html) you can see how to collect them.
[rider-logs-20241122-2214496051936429840036353.zip](https://github.com/user-attachments/files/17878231/rider-logs-20241122-2214496051936429840036353.zip)

**System information:**
 - OS: MacOS
 - .NET version: 9.0
 - JetBrains Rider version:  2024.3
 - Aspire plugin version: 1.6.0
 - Aspire workload version: N/A for .NET 9

**Workaround**
1. Delete AppHost run Configurations
2. Delete .NET Launch settings Configurations
3. Add new AppHost configurations

**Comment by mountain65** [comment]
Your workaround helped me, thanks!
