### ISSUE TITLE
Add ability to launch projects with dotnet watch

### ISSUE THREAD

**Issue by Juulsn** [JetBrains/aspire-plugin#309]
As far as I know, there isn't a way currently to launch projects with dotnet watch.

### Expected behaviour

It would be ideal if we could enable dotnet watch functionality for the projects similar to how it’s executed for the AppHost project when running it with dotnet watch.

### Current behaviour 

The plugin launches the projects directly. Configuring profiles doesn't work to my knowledge.

The only workaround is to configure the Project as a custom Executable in the AppHost, but that introduces other problems.

**Comment by rafaelldi** [comment]
Hello! The plugin uses Rider's Hot Reload technology (you can read more [here](https://www.jetbrains.com/help/rider/Hot_Reload.html)), and we don't plan to support `dotnet-watch`.

**Comment by Juulsn** [comment]
To be honest, in my opinion this is a **very bad choice**.
Even though Rider is an awesome IDE, hot reload is pretty much not usable for almost all cases. 
You have to restart the project more often than being able to "click" Apply Changes.

That being said - this is a deal breaker for me and stops me from using the aspire plugin at all :/
I hope you can reconsider this.

**Comment by rafaelldi** [comment]
`dotnet watch` and Rider Hot Reload use the same technology underneath, so theoretically there should be no differences between them. If you have any problems with Rider Hot Reload, it would help us a lot if you create an issue in [our tracker](https://youtrack.jetbrains.com/issues/RIDER) and my colleagues will fix it.
Sorry to hear that, but from the plugin point of view, it takes a lot of resources to not use an already existing mechanism and try to integrate with something external.
